/**
 * Default exercise library.
 *
 * This is the canonical list of exercises seeded into the database.
 * Each entry defines the exercise name, primary muscle group, and
 * required equipment. These are inserted as global (non-custom)
 * exercises available to all users.
 *
 * The `id` field is omitted here because IDs are generated by the
 * database at seed/insert time. The `isCustom` and `createdBy`
 * fields are also omitted since all default exercises are global
 * (`isCustom = false`, `createdBy = null`).
 */

import { MuscleGroup, Equipment } from '../types/workout';

export interface DefaultExercise {
  name: string;
  muscleGroup: MuscleGroup;
  equipment: Equipment;
}

export const DEFAULT_EXERCISES: DefaultExercise[] = [
  // ── Chest ──────────────────────────────────────────────────────
  { name: 'Barbell Bench Press', muscleGroup: 'chest', equipment: 'barbell' },
  { name: 'Incline Barbell Bench Press', muscleGroup: 'chest', equipment: 'barbell' },
  { name: 'Dumbbell Bench Press', muscleGroup: 'chest', equipment: 'dumbbell' },
  { name: 'Incline Dumbbell Bench Press', muscleGroup: 'chest', equipment: 'dumbbell' },
  { name: 'Dumbbell Fly', muscleGroup: 'chest', equipment: 'dumbbell' },
  { name: 'Cable Fly', muscleGroup: 'chest', equipment: 'cable' },
  { name: 'Machine Chest Press', muscleGroup: 'chest', equipment: 'machine' },
  { name: 'Push-ups', muscleGroup: 'chest', equipment: 'bodyweight' },
  { name: 'Dips', muscleGroup: 'chest', equipment: 'bodyweight' },

  // ── Back ───────────────────────────────────────────────────────
  { name: 'Deadlift', muscleGroup: 'back', equipment: 'barbell' },
  { name: 'Barbell Row', muscleGroup: 'back', equipment: 'barbell' },
  { name: 'Dumbbell Row', muscleGroup: 'back', equipment: 'dumbbell' },
  { name: 'Pull-ups', muscleGroup: 'back', equipment: 'bodyweight' },
  { name: 'Chin-ups', muscleGroup: 'back', equipment: 'bodyweight' },
  { name: 'Lat Pulldown', muscleGroup: 'back', equipment: 'cable' },
  { name: 'Seated Cable Row', muscleGroup: 'back', equipment: 'cable' },
  { name: 'T-Bar Row', muscleGroup: 'back', equipment: 'barbell' },

  // ── Shoulders ──────────────────────────────────────────────────
  { name: 'Overhead Press', muscleGroup: 'shoulders', equipment: 'barbell' },
  { name: 'Dumbbell Shoulder Press', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { name: 'Lateral Raise', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { name: 'Front Raise', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { name: 'Face Pull', muscleGroup: 'shoulders', equipment: 'cable' },
  { name: 'Reverse Fly', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { name: 'Arnold Press', muscleGroup: 'shoulders', equipment: 'dumbbell' },

  // ── Legs ───────────────────────────────────────────────────────
  { name: 'Barbell Squat', muscleGroup: 'legs', equipment: 'barbell' },
  { name: 'Front Squat', muscleGroup: 'legs', equipment: 'barbell' },
  { name: 'Leg Press', muscleGroup: 'legs', equipment: 'machine' },
  { name: 'Romanian Deadlift', muscleGroup: 'legs', equipment: 'barbell' },
  { name: 'Leg Extension', muscleGroup: 'legs', equipment: 'machine' },
  { name: 'Leg Curl', muscleGroup: 'legs', equipment: 'machine' },
  { name: 'Bulgarian Split Squat', muscleGroup: 'legs', equipment: 'dumbbell' },
  { name: 'Calf Raise', muscleGroup: 'legs', equipment: 'machine' },
  { name: 'Hip Thrust', muscleGroup: 'legs', equipment: 'barbell' },
  { name: 'Lunges', muscleGroup: 'legs', equipment: 'dumbbell' },

  // ── Arms ───────────────────────────────────────────────────────
  { name: 'Barbell Curl', muscleGroup: 'arms', equipment: 'barbell' },
  { name: 'Dumbbell Curl', muscleGroup: 'arms', equipment: 'dumbbell' },
  { name: 'Hammer Curl', muscleGroup: 'arms', equipment: 'dumbbell' },
  { name: 'Cable Curl', muscleGroup: 'arms', equipment: 'cable' },
  { name: 'Tricep Pushdown', muscleGroup: 'arms', equipment: 'cable' },
  { name: 'Overhead Tricep Extension', muscleGroup: 'arms', equipment: 'dumbbell' },
  { name: 'Skull Crushers', muscleGroup: 'arms', equipment: 'barbell' },
  { name: 'Close-Grip Bench Press', muscleGroup: 'arms', equipment: 'barbell' },

  // ── Core ───────────────────────────────────────────────────────
  { name: 'Plank', muscleGroup: 'core', equipment: 'bodyweight' },
  { name: 'Hanging Leg Raise', muscleGroup: 'core', equipment: 'bodyweight' },
  { name: 'Cable Crunch', muscleGroup: 'core', equipment: 'cable' },
  { name: 'Ab Wheel Rollout', muscleGroup: 'core', equipment: 'bodyweight' },
  { name: 'Russian Twist', muscleGroup: 'core', equipment: 'bodyweight' },
];
